version: '3.8'
services:
  bff:
    build: 
      context: ./bff/target
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - backend

  frontend:
    build: ./front/browser
    ports:
      - "80:80"
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  webnet:
  backend:

